steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - sgtm_cloud_run_updater  
  - --region=europe-west3
  - --source=.
  - --trigger-http
  - --runtime=python39  
  - --entry-point=check_cloud_run  
  - --allow-unauthenticated

# specific service account:
#  - --service-account=your-service-account@your-project.iam.gserviceaccount.com
# Dont forget to set cloud build permissions in gcp cloud console settings